// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import ParticleBackground from "@/components/particle-background";
import Footer from "@/components/footer";
import { cn } from "@/lib/utils";
import FloatingContact from "@/components/FloatingContact";
import Link from "next/link";
import { Sparkles } from "lucide-react";

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "LUXE MOTORS | Premium Automotive Marketplace",
  description:
    "Discover an exclusive collection of car parts. get quality parts for hypercars to electric marvels, find your next masterpiece at BimmerPartAuto.",
  keywords: [
    "luxury cars",
    "hypercar parts",
    "sports cars",
    "premium car parts",
    "car marketplace",
    "automotive",
    "supercar",
    "electric parts",
  ],
  openGraph: {
    title: "BIMMERPARTS | Premium Automotive Marketplace",
    description:
      "Discover the world's most extraordinary car parts at BimmerParts.",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className="bg-surface text-white antialiased">
        <ParticleBackground />
        <Navbar />
        <main className="relative z-10">{children}</main>
        <FloatingContact />
        <Footer />
      </body>
    </html>
  );
}